theme: jekyll-theme-cayman
title: "The Impact of Conditional Cash Transfers on Maternal Autonomy in Nigeria"
description: "SUREP Research Paper · Airah Balogun · University of San Francisco, 2025"
show_downloads: false
